### PR TITLE
Allow `auth` options to be a function instead of a static object

### PR DESCRIPTION
**Pull request by brettjonesdev**
We have a realtime application which has an `authEndpoint` which changes dynamically as JWTs expire and refresh. 

`pusher-js-auth` does not currently support dynamic changes to the `auth` configuration. 

This PR allows the `auth` option to be a function, which will be dynamically invoked at request time. For example: 

```javascript
const pusher = new PusherClient({
  authEndpoint: '/v1/pusher/auth',
  auth: () => ({
    headers: {
      'Bearer': getDynamicBearerToken()
    }
  })
})
```

### CODE REVIEW

**Comment by morloderex** [comment]
I like this!.. It should be merged in.

**Comment by dirkbonhomme** [comment]
Thanks for this update @brettjonesdev!
I've released the changes as 3.0.1 on Github and NPM

**Comment by marcellobarile** [comment]
I'm struggling to update the token in such a way when async/await needs to be used.

**Comment by stof** [comment]
@marcellobarile the function-based option indeed requires returning a synchronous result. It does not support return a promise (and even less an object with a promise in one of its properties)

**Comment by marcellobarile** [comment]
@stof thanks for the reply, what if I propose a PR for covering the case? It would be quite easy since you already support the `authOptions` being a function.

To give a bit of perspective, I'm trying to cope with the necessity to refresh the token before consuming it. Since the token refresh is typically something asynchronous (since it involves interacting with the auth server) it would be easier being able to pass an async function as `authOptions`, or do you see other options?

**Comment by stof** [comment]
this is not as easy as it sounds in your comment. `composeQuery` is a synchronous function right now. Supporting an async logic requires making `composeQuery` asynchronous (and then checking its callers, etc)

**Comment by marcellobarile** [comment]
I see that `composeQuery` is used only in `xhrRequest`, which in my case will be marked as `async` and will be in charge of handling the `authOptions` before instantiating the XHR request.

I'm already providing a fix since this case is blocking us from proceeding with the integration of `pusher-js-auth`. I'm going to open the PR anyway, in the worst cases scenario we will keep the forked repo and maintain it for our purposes.

**Pull request merged**
