### PR TITLE
Add type definitions for the library

### PR DESCRIPTION
**Pull request by stof**
This adds type definitions in the library, making it easier to use this library in typescript.

Most of the typing is actually done by pusher-js itself. I simply document the fact that the exported function implements the `AuthorizerGenerator` type of pusher-js.
However, I also extend the `AuthorizerOptions` type to document the `authDelay` option that is being added by that authorizer.

### CODE REVIEW

**Comment by dirkbonhomme** [comment]
Thanks a lot!

**Comment by stof** [comment]
@dirkbonhomme can you make a new release ?

**Comment by dirkbonhomme** [comment]
Done!

**Comment by stof** [comment]
thanks

**Pull request merged**
